

package org.cvut.vrchlpet.MEditor.dialogs;


import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.filechooser.FileFilter;

import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.cvut.vrchlpet.MCore.core.Element;
import org.cvut.vrchlpet.MCore.visualization.BackgroundColor;
import org.cvut.vrchlpet.MCore.visualization.BackgroundImage;
import org.cvut.vrchlpet.MCore.visualization.MBorder;
import org.cvut.vrchlpet.MCore.visualization.ElementLabel;
import org.cvut.vrchlpet.MCore.visualization.ElementVisualization;
import org.cvut.vrchlpet.MCore.visualization.Layout;
import org.cvut.vrchlpet.MCore.visualization.ui.ElementUI;

/**
 *
 * Napul generovany, napul implementovany panel dialogu pro editaci grafiky elementu
 *
 * @author Vrchlavsky Petr
 * @version 1.0
 */
public class ElementUIPanel extends javax.swing.JPanel implements ActionListener, ItemListener{

    private Element element;
    private JDialog container;


    /** Creates new form ElementUIPanel */
    public ElementUIPanel(Element element, JDialog container) {
        initComponents();
        this.element = element;
        this.container = container;
        fillForm(element);
        freezLableSettings();

        btLoadImage.addActionListener(this);
        btSet.addActionListener(this);
        chbAbsolute.addActionListener(this);
        chbResizable.addActionListener(this);
        chbVisible.addActionListener(this);
        btAdd.addActionListener(this);
        btOk.addActionListener(this);
        btRemove.addActionListener(this);
        listCurrent.addItemListener(this);
        chLayout.addItemListener(this);
        btSetPosition.addActionListener(this);
        btChangeText.addActionListener(this);
        btDelete.addActionListener(this);
    }

    public void close() {
        
    }

    private void fillForm(Element el) {
        ElementVisualization ev = ((ElementUI)el.getUi()).getVisualization();
        lbElementName.setText(el.getNameSpace());
        if ( ev.getBackgroundImage() != null)
            txImange.setText(ev.getBackgroundImage().getImgName());

        if ( ev.getBorder() != null) {
            chbResizable.setSelected(ev.getBorder().isResizable());
            chbVisible.setSelected(ev.getBorder().isVisible());
        }
        if ( ev.getBackgroundColor() != null)
            jpColor.setBackground(ev.getBackgroundColor().getColor());

        listCurrent.removeAll();
        for ( ElementLabel elb : ev.getLabels()) {
            listCurrent.add(elb.getText());
        }

        chLayout.removeAll();
        for ( Layout l : Layout.values()) {
            chLayout.add(l.name());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbElementName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txImange = new javax.swing.JTextField();
        btLoadImage = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chbVisible = new javax.swing.JCheckBox();
        chbResizable = new javax.swing.JCheckBox();
        btDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jpColor = new javax.swing.JPanel();
        btSet = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        listCurrent = new java.awt.List();
        btAdd = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        chLayout = new java.awt.Choice();
        jLabel3 = new javax.swing.JLabel();
        chbAbsolute = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txX = new javax.swing.JTextField();
        txY = new javax.swing.JTextField();
        btSetPosition = new javax.swing.JButton();
        btChangeText = new javax.swing.JButton();
        btOk = new javax.swing.JButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jLabel1.text")); // NOI18N

        lbElementName.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.lbElementName.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jPanel1.border.title"))); // NOI18N

        txImange.setEditable(false);
        txImange.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.txImange.text")); // NOI18N

        btLoadImage.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.btLoadImage.text")); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jPanel2.border.title"))); // NOI18N

        chbVisible.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.chbVisible.text")); // NOI18N

        chbResizable.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.chbResizable.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbVisible)
                    .addComponent(chbResizable))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(chbVisible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbResizable))
        );

        btDelete.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.btDelete.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txImange, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btLoadImage)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(txImange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLoadImage)
                    .addComponent(btDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jPanel3.border.title"))); // NOI18N

        jpColor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpColorLayout = new javax.swing.GroupLayout(jpColor);
        jpColor.setLayout(jpColorLayout);
        jpColorLayout.setHorizontalGroup(
            jpColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );
        jpColorLayout.setVerticalGroup(
            jpColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        btSet.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.btSet.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSet)
                .addGap(18, 18, 18)
                .addComponent(jpColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jPanel5.border.title"))); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jLabel2.text")); // NOI18N

        btAdd.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.btAdd.text")); // NOI18N

        btRemove.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.btRemove.text")); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jPanel6.border.title"))); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jLabel3.text")); // NOI18N

        chbAbsolute.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.chbAbsolute.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.jLabel5.text")); // NOI18N

        txX.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.txX.text")); // NOI18N
        txX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txXActionPerformed(evt);
            }
        });

        txY.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.txY.text")); // NOI18N

        btSetPosition.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.btSetPosition.text")); // NOI18N

        btChangeText.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.btChangeText.text")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(chbAbsolute)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txX, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txY, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btChangeText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSetPosition)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbAbsolute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChangeText)
                    .addComponent(btSetPosition))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(99, 99, 99))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(btAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRemove)))
                    .addComponent(listCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRemove)
                            .addComponent(btAdd)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btOk.setText(org.openide.util.NbBundle.getMessage(ElementUIPanel.class, "ElementUIPanel.btOk.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbElementName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btOk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbElementName))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txXActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btChangeText;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btLoadImage;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btSet;
    private javax.swing.JButton btSetPosition;
    private java.awt.Choice chLayout;
    private javax.swing.JCheckBox chbAbsolute;
    private javax.swing.JCheckBox chbResizable;
    private javax.swing.JCheckBox chbVisible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jpColor;
    private javax.swing.JLabel lbElementName;
    private java.awt.List listCurrent;
    private javax.swing.JTextField txImange;
    private javax.swing.JTextField txX;
    private javax.swing.JTextField txY;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();

        if ( o == btLoadImage) {
            JFileChooser chooser = new JFileChooser();
            // Note: source for ExampleFileFilter can be found in FileChooserDemo,
            // under the demo/jfc directory in the Java 2 SDK, Standard Edition.

            MyFilter filter = new MyFilter();
            chooser.setFileFilter(filter);
            int returnVal = chooser.showOpenDialog(this);
            File file = null;
            if(returnVal == JFileChooser.APPROVE_OPTION) {
               file = chooser.getSelectedFile();
            }

            if ( file != null) {
                BackgroundImage im = new BackgroundImage(file.getAbsolutePath());
                ((ElementUI)element.getUi()).getVisualization().setBackgroundImage(im);
                fillForm(element);
            }

        } else if ( o == btAdd) {
            String text = JOptionPane.showInputDialog(this, "Type in the text of the label:", "");
            if ( text != null) {
                ElementLabel l = new ElementLabel();
                l.setText(text);
                ((ElementUI)element.getUi()).getVisualization().getLabels().add(l);
                listCurrent.add(l.getText());
            }
        } else if ( o == btOk) {
            container.dispose();
        } else if ( o == btRemove) {
            int index = listCurrent.getSelectedIndex();
            if ( index == -1) {
                DialogMessagesManager.showErrorDialog("Select the lable first");
                return;
            }

            ElementLabel l = ((ElementUI)element.getUi()).getVisualization().getLabels().get(index);
            ((ElementUI)element.getUi()).getVisualization().getLabels().remove(l);
            listCurrent.remove(index);
            listCurrent.select(-1);
            freezLableSettings();
        } else if ( o == btSet) {
            Color newColor = JColorChooser.showDialog(
                     this,
                     "Choose Background Color",
                     Color.white);

            if ( newColor == null)
                return;

            BackgroundColor bc = new BackgroundColor(newColor);
            ((ElementUI)element.getUi()).getVisualization().setBackgroundColor(bc);
            jpColor.setBackground(newColor);
        } else if ( o == chbAbsolute) {
            int index = listCurrent.getSelectedIndex();
            if ( index == -1) {
                DialogMessagesManager.showErrorDialog("Select the lable first");
                return;
            }

            ElementLabel l = ((ElementUI)element.getUi()).getVisualization().getLabels().get(index);
            if ( chbAbsolute.isSelected()) {
                txX.setEnabled(true);
                txY.setEnabled(true);
                btSetPosition.setEnabled(true);
                l.getLabelPosition().setAbsolute(true);
                chLayout.setEnabled(false);
            } else {
                txX.setEnabled(false);
                txY.setEnabled(false);
                l.getLabelPosition().setAbsolute(false);
                btSetPosition.setEnabled(false);
                chLayout.setEnabled(true);
            }

        } else if ( o == chbVisible) {
            MBorder bor = ((ElementUI)element.getUi()).getVisualization().getBorder();
            if ( bor == null) {
                bor = new MBorder();
                ((ElementUI)element.getUi()).getVisualization().setBorder(bor);
            }
            bor.setVisible(chbVisible.isSelected());
        } else if ( o == chbResizable) {
            MBorder bor = ((ElementUI)element.getUi()).getVisualization().getBorder();
            if ( bor == null) {
                bor = new MBorder();
                ((ElementUI)element.getUi()).getVisualization().setBorder(bor);
            }
            bor.setResizable(chbResizable.isSelected());
        } else if ( o == btSetPosition) {
            int index = listCurrent.getSelectedIndex();
            if ( index == -1) {
                DialogMessagesManager.showErrorDialog("Select the lable first");
                return;
            }
            
            try {
                int x = Integer.parseInt(txX.getText());
                int y = Integer.parseInt(txY.getText());
                ElementLabel l = ((ElementUI)element.getUi()).getVisualization().getLabels().get(index);
                l.getLabelPosition().setX(x);
                l.getLabelPosition().setY(y);
            } catch ( NumberFormatException ex) {
                DialogMessagesManager.showErrorDialog("Bad number format!");
                return;
            }
        } else if ( o == btChangeText) {
            int index = listCurrent.getSelectedIndex();
            if ( index == -1) {
                DialogMessagesManager.showErrorDialog("Select the lable first");
                return;
            }

            ElementLabel l = ((ElementUI)element.getUi()).getVisualization().getLabels().get(index);
            String s = JOptionPane.showInputDialog(this, "Type in the text of the label",l.getText());
            if ( s == null)
                return;

            l.setText(s);
            listCurrent.replaceItem(l.getText(), index);
        } else if ( o == btDelete) {
            ((ElementUI)element.getUi()).getVisualization().setBackgroundImage(null);
            txImange.setText("");
        }
    }

    private void freezLableSettings() {
        listCurrent.select(-1);
        txX.setText("0");
        txY.setText("0");
        txX.setEnabled(false);
        txY.setEnabled(false);
        chbAbsolute.setEnabled(false);
        chbAbsolute.setSelected(false);
        chLayout.setEnabled(false);
        btSetPosition.setEnabled(false);
        btChangeText.setEnabled(false);
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        Object o = e.getSource();

        if ( o == listCurrent) {
            int index = listCurrent.getSelectedIndex();
            ElementLabel l = ((ElementUI)element.getUi()).getVisualization().getLabels().get(index);
            if ( l.getLabelPosition().isAbsolute()) {
                txX.setEnabled(true);
                txY.setEnabled(true);
                txX.setText("" + l.getLabelPosition().getX());
                txY.setText("" + l.getLabelPosition().getY());
                chbAbsolute.setSelected(true);
                chbAbsolute.setEnabled(true);
                btSetPosition.setEnabled(true);
                btChangeText.setEnabled(true);
                chLayout.setEnabled(false);
            } else {
                txX.setEnabled(false);
                txY.setEnabled(false);
                chLayout.setEnabled(true);
                chbAbsolute.setEnabled(true);
                chbAbsolute.setSelected(false);
                btSetPosition.setEnabled(false);
                btChangeText.setEnabled(true);
                for ( int i = 0; i < chLayout.getItemCount(); i++) {
                    if ( l.getLabelPosition().getLayout().name().equals(chLayout.getItem(i))) {
                        chLayout.select(i);
                        return;
                    }
                }
            }
            
        } else if ( o == chLayout) {
            int index = listCurrent.getSelectedIndex();
            if ( index == -1) {
                DialogMessagesManager.showErrorDialog("Select the lable first");
                return;
            }

            ElementLabel l = ((ElementUI)element.getUi()).getVisualization().getLabels().get(index);
            l.getLabelPosition().setLayout(Layout.valueOf(chLayout.getSelectedItem()));
        }
    }



    private class MyFilter extends FileFilter {

        ArrayList<String> extentions = new ArrayList<String>();

        public MyFilter() {
            extentions.add(".jpg");
            extentions.add(".JPG");
            extentions.add(".jpeg");
            extentions.add(".JPEG");
            extentions.add(".png");
            extentions.add(".PNG");
            extentions.add(".bmp");
            extentions.add(".BMP");
            //extentions.add(".gif");
            //extentions.add(".GIF");
            //extentions.add(".svg");
            //extentions.add(".SVG");

        }

        @Override
        public boolean accept(File f) {
            if ( f.isDirectory())
                return true;

            int index = f.getAbsolutePath().lastIndexOf(".");
            if ( index == -1)
                return false;

            String s = f.getAbsolutePath().substring(index);

            return extentions.contains(s);
        }

        @Override
        public String getDescription() {
            String s = "";
            for ( String ss : extentions) {
                s += "[" + ss + "]";
            }
            return s;
        }

    }

}
